_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.11.0
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.0
            "5": 0.19.10
            "8":
                - 3
                - 5
            "12": 0.19.10
            "13": windows-amd64
algorithm:
    value: PPO
batch_size:
    value: 32
clip_epsilon:
    value: 0.1
epochs:
    value: 6
gamma:
    value: 0.99
hidden_dim:
    value: 256
learning_rate:
    value: 0.0001
n_actions:
    value: 2
n_observations:
    value: 180
